# Generated by Django 4.0.4 on 2022-05-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=96)),
                ('last_name', models.CharField(max_length=96)),
                ('user_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birthday_year', models.PositiveIntegerField()),
            ],
        ),
    ]
